name       : zsh-syntax-highlighting
version    : 0.6.0
release    : 2
source     :
    - https://github.com/zsh-users/zsh-syntax-highlighting/archive/0.6.0.tar.gz : e69db483e20228b72ccfa401e9ad6cf80d6edb48c68acca9102b50b311821b84
license    : BSD-3-Clause
component  : system.utils
summary    : Fish shell like syntax highlighting for ZSH
description: |
    This package provides syntax highlighing for the ZSH shell. It enables highlighting of commands
    while they are typed at a ZSH prompt into an interactive terminal. This helps in reviewing
    commands before running them, particularly in catching syntax errors.
install    : |
    %make_install PREFIX=/usr
